version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: medusa_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: medusa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: medusa_redis
    ports:
      - "6379:6379"

  medusa:
    build: .
    container_name: medusa_server
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    env_file:
      - .env

volumes:
  pgdata:
